### ISSUE TITLE
'v8::Object::Set': no overloaded function takes 2 arguments

### ISSUE THREAD

**Issue by si458** [Aldaviva/lock-your-windows#5]
```
c:\users\simon\documents\ourmonitoring\nodejs\node_modules\lock-your-windows\src\main\c++\bindings.cpp(13):
error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments
[C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\lock-your-windows\build\winlock.vcxproj]
c:\users\simon\documents\ourmonitoring\nodejs\node_modules\lock-your-windows\src\main\c++\bindings.cpp(14):
error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments
[C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\lock-your-windows\build\winlock.vcxproj]
```

**Comment by si458** [comment]
@bsnk-dev this is really from your repo and your code with the fix,
but created issue here as it happens in this repo too
Node 14.17.1, Windows 10, x64

**Comment by Aldaviva** [comment]
Fixed by passing the `CreationContext` as the first argument to `exports->Set` as seen in the [nodejs/node-addon-examples nan example 1](https://github.com/nodejs/node-addon-examples/blob/8c093b82905b78d6371487e9feb07593a3f729da/1_hello_world/nan/hello.cc#L8).

Built successfully with Node 14.17.3 LTS and Visual Studio 2017 15.9.28307.1525 and tested on Windows 10 x64.

Deployed to npm as [`lock-your-windows@0.0.1`](https://www.npmjs.com/package/lock-your-windows/v/0.0.1).
